name: Build LaTeX document

on:
  push:
    branches:
      - main
      - add_github_actions # only for test purposes
  pull_request:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Documentation/Doku.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Documentation/Bachelor_Thesis.pdf
